INSERT INTO TBL_CATEGORY (NAME) VALUES ('Fabricação Própria');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Nacional');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Importado');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Premium');

INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, NEW_PRODUCT, PROMOTION, CATEGORY_ID) VALUES ('PRODUCTO 1', 'PRODUCTO AUTO',1425,TRUE,FALSE,3);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, NEW_PRODUCT,PROMOTION,CATEGORY_ID) VALUES ('PRODUCTO 2', 'PRODUCTO AUTO 2',250,FALSE,TRUE,4);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, NEW_PRODUCT,PROMOTION,CATEGORY_ID) VALUES ('PRODUCTO 3', 'PRODUCTO AUTO 3',15,FALSE,FALSE,2);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, NEW_PRODUCT,PROMOTION,CATEGORY_ID) VALUES ('PRODUCTO 4', 'PRODUCTO AUTO 4',2210,TRUE,TRUE,2);